# Dependencies
markdown:         kramdown
highlight:        pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thiago Cardoso
tagline:          ''
url:              'http://tncardoso.com'
paginate:         20
baseurl:          /
author:
  name:           'Thiago Cardoso'
  email:          'thiagoncc@gmail.com'
  github:         'tncardoso'
  twitter:        'tncardoso'

